#开发环境
# 配置tomcat端口号
server:
  port: 80
  # 设置tomcat的地址
  # address: localhost   #  本地电脑是这个 192.168.137.1

  # 设置日记的级别
logging:
  level:
    root: warn
    con.jia.blog: debug # 指定这个包下的日记级别为debug

spring:
  #配置 HikariCP数据库连接池(在这配置后,就可以使用了)
  datasource:
    # com.mysql.cj.jdbc.Driver 设置这个后，启动不会报红色日记，因为升级后的mysql驱动类，Driver位置由com.mysql.jdbc.Driver 变为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # xxx/表名后面要加?serverTimezone=UTC : 因为mysql 6+ 版本改变了一些东西
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 1234
  redis: # 设置redis的主机地址和端口号
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8 #最大连接池数 复数为没有限制
    timeout: 30000 #连接超时时间
  profiles:
    active:

mybatis:
  #实体类别名包的路径
  type-aliases-package: com.jia.blog.pojo
  #映射文件的路径 （有需要时可以使用）
  mapper-locations: classpath:com.jia.mapper/*.xml

  configuration:
    #指定日记级别，这里指定的是在后台输入的日记类型
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
