server:
  port: 80
  #address: 192.168.0.105
logging:
  level:
    root: warn
    con.jia.blog: info
spring:
  datasource:
    # com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.jia.blog.pojo

